version: "2"
services:
  app:
    container_name: chat-server
    restart: always
    build: .
    ports:
      - "3020:3020"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"