version: '3'
services:
  web:
    image: docker-chat-server
    build: ./
    command: npm start
    ports:
      - "3020:3020"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"